/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function minus(a: number, b: number): number
export function mul(a: number, b: number): number
export function div(a: number, b: number): number
